# Generated by Django 3.2.7 on 2021-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_createuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
