# Generated by Django 3.2.7 on 2021-09-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_createuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='password1',
        ),
        migrations.AlterField(
            model_name='createuser',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
