# Generated by Django 3.2.7 on 2021-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210928_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
