# Generated by Django 3.2.7 on 2021-09-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_createuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='password2',
        ),
    ]
